<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.5.2" />
    <PackageVersion Include="Dapper" Version="2.1.66" />
    <PackageVersion Include="EFCore.NamingConventions" Version="9.0.0" />
    <PackageVersion Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.0" />
    <PackageVersion Include="MediatR" Version="13.1.0" />
    <PackageVersion Include="MediatR.Contracts" Version="2.0.1" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.11" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.11" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.10" />
    <PackageVersion Include="SonarAnalyzer.CSharp" Version="10.11.0.117924" />
  </ItemGroup>
</Project>