<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
	<PackageReference Include="Asp.Versioning.Mvc" />
	<PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" />
	<PackageReference Include="AspNetCore.HealthChecks.NpgSql" />
	<PackageReference Include="AspNetCore.HealthChecks.Redis" />
	<PackageReference Include="AspNetCore.HealthChecks.Uris" />
	<PackageReference Include="Keycloak.NETCore.Client" />
	<PackageReference Include="MailKit" />
	<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
	<PackageReference Include="Microsoft.EntityFrameworkCore" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
	<PackageReference Include="EFCore.NamingConventions" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
	<PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
	<PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Quartz.Extensions.Hosting" />
    <PackageReference Include="Quartz.Serialization.Json" />
    <PackageReference Include="Scriban" />
    <PackageReference Include="Microsoft.Extensions.Resilience" />
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" />
    <PackageReference Include="Stripe.net" />
    <PackageReference Include="Azure.Messaging.ServiceBus" />
    <PackageReference Include="AspNetCore.HealthChecks.AzureServiceBus" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bookify.Application\Bookify.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Data\" />
  </ItemGroup>

  <ItemGroup>
    <None Update="EmailTemplates\*.html">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Quartz\*.sql">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
	<InternalsVisibleTo Include="Bookify.Application.IntegrationTests" />
	<InternalsVisibleTo Include="Bookify.Api.FunctionalTests" />
  </ItemGroup>

</Project>
