name: ci-dev

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch: {}

concurrency:
  group: ci-dev-${{ github.repository }}-${{ github.event.pull_request.head.ref || github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event.pull_request.draft == false

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore Bookify.sln

      - name: Build
        run: dotnet build Bookify.sln --configuration Release --no-restore

      - name: Domain Unit Tests
        run: dotnet test test/Bookify.Domain.UnitTests/Bookify.Domain.UnitTests.csproj --configuration Release --no-build

      - name: Application Unit Tests
        run: dotnet test test/Bookify.Application.UnitTests/Bookify.Application.UnitTests.csproj --configuration Release --no-build

      - name: Api Unit Tests
        run: dotnet test test/Bookify.Api.UnitTests/Bookify.Api.UnitTests.csproj --configuration Release --no-build

      - name: Architecture Tests
        run: dotnet test test/Bookify.ArchitectureTests/Bookify.ArchitectureTests.csproj --configuration Release --no-build

      - name: Application Integration Tests
        run: dotnet test test/Bookify.Application.IntegrationTests/Bookify.Application.IntegrationTests.csproj --configuration Release --no-build
