name: ci

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch: {}  # Allow to triiger the workflow manually

concurrency:
  group: ci-${{ github.workflow }}-${{ github.event.pull_request.head.repo.full_name || github.repository }}-${{ github.event.pull_request.head.ref || github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    if: |
      (github.event_name == 'pull_request' &&
       github.event.pull_request.draft == false &&
       github.head_ref == 'dev') ||
      (github.event_name == 'workflow_dispatch')

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'   

      - name: Cache NuGet
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: ${{ runner.os }}-nuget-

      - name: Restore
        run: dotnet restore Bookify.sln

      - name: Build
        run: dotnet build Bookify.sln --configuration Release --no-restore
