name: temp-test

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Cache NuGet
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: ${{ runner.os }}-nuget-

      - name: Restore
        run: dotnet restore Bookify.sln

      - name: Build
        run: dotnet build Bookify.sln --configuration Release --no-restore

      - name: Run Domain Unit Tests
        run: dotnet test test/Bookify.Domain.UnitTests/Bookify.Domain.UnitTests.csproj --configuration Release --no-build

      - name: Run Application Unit Tests
        run: dotnet test test/Bookify.Application.UnitTests/Bookify.Application.UnitTests.csproj --configuration Release --no-build

      - name: Run Api Unit Tests
        run: dotnet test test/Bookify.Api.UnitTests/Bookify.Api.UnitTests.csproj --configuration Release --no-build

      - name: Run Architecture Tests
        run: dotnet test test/Bookify.ArchitectureTests/Bookify.ArchitectureTests.csproj --configuration Release --no-build

      - name: Run Application Integration Tests
        run: dotnet test test/Bookify.Application.IntegrationTests/Bookify.Application.IntegrationTests.csproj --configuration Release --no-build
